### ISSUE TITLE
Can't save to output TOC with the -o option

### ISSUE THREAD

**Issue by zacklb** [cmcginty/mktoc#6]
The problem is the `_open_file` method in `cmdline.py`.

When you set `-o file.toc`, [the call site](https://github.com/cmcginty/mktoc/blob/02cd0f9d26a656dcf9001e0edf19ddf871b58113/mktoc/cmdline.py#L100) specifies mode='wb' , but `_open_file` tries to [read the file](https://github.com/cmcginty/mktoc/blob/02cd0f9d26a656dcf9001e0edf19ddf871b58113/mktoc/cmdline.py#L138) which errors out. It appears this method was only meant to determine the encoding for an existing file.

**Comment by cmcginty** [comment]
Thanks for reporting this. I'll take a look at this very soon.

**Comment by jdehaan** [comment]
Probably specifying the encoding at the call site removes the problem: would it be ok to tell to create the file for utf-8 encoding even thought the input would be eventually in a different encoding? Or do the encodings have to match?

**Comment by JoeLametta** [comment]
I think that, because of https://github.com/cmcginty/mktoc/pull/8, this issue has been solved and its ticket can be closed: am I right?
